export const RKTR_DEPARTMENTS: string[] = [
  "Design & Engineering",
  "Accounts & Finance",
  "Operations",
  "Machine Shop",
  "Project",
  "Projects - Civil",
  "Forging",
  "Heat Treatment",
  "Purchase & Stores",
  "Maintenance- Automation",
  "Utility Maintenance",
  "Maintenance",
  "Metallurgy & LAB",
  "EHS",
  "Sales & Marketing",
  "IT & Infrastructure",
  "Admin",
  "Human Capital",
  "Design & CAD CAM",
  "Utility Maintenance - EMS",
  "Quality",
  "Die Shop",
];
