export const RKTR_LOCATIONS: string[] = [
  "Security Gate 1",
  "Security Gate 2",
  "Security Gate 3",
  "Canteen Building",
  "EB Room",
  "Electrical Sub Station",
  "MRS Room",
  "Hazardous Storage",
  "Scrap Yard",
  "Cooling Tower MS",
  "Cooling Tower FS",
  "Utility Room 1",
  "Utility Room 2",
  "UPS Room",
  "Machine Shop",
  "Forging Shop",
  "Metallurgy Lab",
  "Heat Treatment",
  "Die Shop",
  "RHF",
  "10K",
  "Wheel Roller",
  "5K",
  "Transfer Conveyor",
  "HTL",
  "Electrical Panel Room 690 Bay 3",
  "690 Bay 1",
  "EOT Bay 1",
  "EOT Bay 2",
  "EOT Bay 3",
  "EOT Bay 4",
  "Propane Yard",
  "UG Sump Room",
  "ETP & STP",
];
