/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AttachmentMeta = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Text,
  'storageHash' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'uploadedAt' : IDL.Int,
});
export const RecordId = IDL.Text;
export const CapaStatus = IDL.Variant({
  'closed' : IDL.Null,
  'verified' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CapaRecord = IDL.Record({
  'id' : RecordId,
  'status' : CapaStatus,
  'title' : IDL.Text,
  'owner' : IDL.Text,
  'createdAt' : Timestamp,
  'actionPlan' : IDL.Text,
  'verificationDetails' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'targetDate' : Timestamp,
  'department' : IDL.Text,
  'rootCause' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const DepartmentRecord = IDL.Record({
  'id' : RecordId,
  'head' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const ESGStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const ESGSocial = IDL.Record({
  'womenInWorkforce' : IDL.Float64,
  'occupationalHealthCases' : IDL.Float64,
  'fatalities' : IDL.Float64,
  'genderDiversityRatio' : IDL.Float64,
  'trir' : IDL.Float64,
  'employeeSatisfactionIndex' : IDL.Float64,
  'ltifr' : IDL.Float64,
  'contractorSafetyPerformance' : IDL.Float64,
  'absenteeismRate' : IDL.Float64,
  'grievanceCases' : IDL.Float64,
  'trainingHoursPerEmployee' : IDL.Float64,
  'communityEngagementPrograms' : IDL.Float64,
  'employeeTurnoverRate' : IDL.Float64,
});
export const UserId = IDL.Text;
export const ESGEnvironmental = IDL.Record({
  'wasteRecyclingRate' : IDL.Float64,
  'envComplianceViolations' : IDL.Float64,
  'renewableEnergyUsage' : IDL.Float64,
  'waterReuseRate' : IDL.Float64,
  'energyConsumption' : IDL.Float64,
  'waterIntensity' : IDL.Float64,
  'waterConsumption' : IDL.Float64,
  'carbonEmissionIntensity' : IDL.Float64,
  'wasteGenerated' : IDL.Float64,
});
export const ESGGovernance = IDL.Record({
  'antiCorruptionTrainingCoverage' : IDL.Float64,
  'complianceBreaches' : IDL.Float64,
  'regulatoryViolations' : IDL.Float64,
  'whistleblowerComplaints' : IDL.Float64,
  'codeOfConductViolations' : IDL.Float64,
  'policyComplianceScore' : IDL.Float64,
  'dataPrivacyIncidents' : IDL.Float64,
  'regulatoryPenalties' : IDL.Float64,
});
export const ESGRecord = IDL.Record({
  'id' : RecordId,
  'status' : ESGStatus,
  'periodType' : IDL.Text,
  'dataSource' : IDL.Text,
  'social' : ESGSocial,
  'period' : IDL.Text,
  'approvedAt' : Timestamp,
  'approvedBy' : IDL.Text,
  'recordedAt' : Timestamp,
  'recordedBy' : UserId,
  'recordedByName' : IDL.Text,
  'notes' : IDL.Text,
  'environmental' : ESGEnvironmental,
  'governance' : ESGGovernance,
  'department' : IDL.Text,
});
export const EnvironmentRecord = IDL.Record({
  'id' : RecordId,
  'value' : IDL.Float64,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'recordType' : IDL.Text,
  'recordedBy' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const IncidentStatus = IDL.Variant({
  'closed' : IDL.Null,
  'submitted' : IDL.Null,
  'escalated' : IDL.Null,
  'underReview' : IDL.Null,
  'approved' : IDL.Null,
  'overdue' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const PersonInvolved = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'employeeId' : IDL.Text,
  'injuryType' : IDL.Text,
  'department' : IDL.Text,
});
export const IncidentRecord = IDL.Record({
  'id' : RecordId,
  'status' : IncidentStatus,
  'title' : IDL.Text,
  'teamLead' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'areaBarricaded' : IDL.Opt(IDL.Bool),
  'description' : IDL.Text,
  'personsInvolved' : IDL.Opt(IDL.Vec(PersonInvolved)),
  'ticketNumber' : IDL.Text,
  'teamMembers' : IDL.Opt(IDL.Vec(IDL.Text)),
  'updatedAt' : Timestamp,
  'reportedBy' : IDL.Text,
  'medicalTreatment' : IDL.Opt(IDL.Bool),
  'investigationDueDate' : IDL.Opt(IDL.Text),
  'targetDate' : IDL.Opt(IDL.Text),
  'natureOfInjury' : IDL.Opt(IDL.Text),
  'actionsTaken' : IDL.Opt(IDL.Text),
  'rootCauseCategory' : IDL.Opt(IDL.Text),
  'severity' : IDL.Text,
  'bodyPartAffected' : IDL.Opt(IDL.Text),
  'contributingFactors' : IDL.Opt(IDL.Vec(IDL.Text)),
  'department' : IDL.Text,
  'firstAidGiven' : IDL.Opt(IDL.Bool),
  'correctiveAction' : IDL.Opt(IDL.Text),
  'daysLost' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
  'attachments' : IDL.Opt(IDL.Vec(AttachmentMeta)),
  'rootCause' : IDL.Opt(IDL.Text),
  'responsiblePerson' : IDL.Opt(IDL.Text),
});
export const InspectionStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const InspectionRecord = IDL.Record({
  'id' : RecordId,
  'status' : InspectionStatus,
  'inspectionDate' : Timestamp,
  'title' : IDL.Text,
  'area' : IDL.Text,
  'createdAt' : Timestamp,
  'score' : IDL.Nat,
  'findings' : IDL.Vec(IDL.Text),
  'inspector' : IDL.Text,
});
export const ObservationStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ObservationType = IDL.Variant({
  'unsafeAct' : IDL.Null,
  'nearMiss' : IDL.Null,
  'unsafeCondition' : IDL.Null,
});
export const ObservationRecord = IDL.Record({
  'id' : RecordId,
  'status' : ObservationStatus,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'actions' : IDL.Vec(IDL.Text),
  'reportedBy' : IDL.Text,
  'obsType' : ObservationType,
  'location' : IDL.Text,
  'attachments' : IDL.Opt(IDL.Vec(AttachmentMeta)),
});
export const PermitStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'submitted' : IDL.Null,
  'underReview' : IDL.Null,
  'validated' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const GasTestResults = IDL.Record({
  'oxygenLevel' : IDL.Text,
  'testTime' : IDL.Text,
  'testedBy' : IDL.Text,
  'toxicGas' : IDL.Text,
  'flammableGas' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});
export const PermitType = IDL.Variant({
  'confinedSpace' : IDL.Null,
  'heightWork' : IDL.Null,
  'lineBreaking' : IDL.Null,
  'hotWork' : IDL.Null,
  'electrical' : IDL.Null,
  'excavation' : IDL.Null,
});
export const PermitSignatures = IDL.Record({
  'safetyOfficerSignature' : IDL.Text,
  'requestedBySignature' : IDL.Text,
  'supervisorSignature' : IDL.Text,
});
export const HazardControl = IDL.Record({
  'control' : IDL.Text,
  'residualRisk' : IDL.Text,
  'hazard' : IDL.Text,
});
export const ToolboxTalk = IDL.Record({
  'keyPoints' : IDL.Text,
  'conductedAt' : IDL.Text,
  'conductedBy' : IDL.Text,
  'attendeesCount' : IDL.Nat,
});
export const PermitRecord = IDL.Record({
  'id' : RecordId,
  'startTime' : Timestamp,
  'status' : PermitStatus,
  'isolationVerifiedBy' : IDL.Opt(IDL.Text),
  'hazards' : IDL.Vec(IDL.Text),
  'endTime' : Timestamp,
  'permitNumber' : IDL.Text,
  'lotoApplied' : IDL.Opt(IDL.Bool),
  'approvedBy' : IDL.Opt(IDL.Text),
  'ppeRequired' : IDL.Vec(IDL.Text),
  'jobDescription' : IDL.Text,
  'createdAt' : Timestamp,
  'gasTestResults' : IDL.Opt(GasTestResults),
  'emergencyContacts' : IDL.Opt(IDL.Vec(EmergencyContact)),
  'reviewedBy' : IDL.Opt(IDL.Text),
  'permitType' : PermitType,
  'isolationTypes' : IDL.Opt(IDL.Vec(IDL.Text)),
  'signatures' : IDL.Opt(PermitSignatures),
  'hazardControls' : IDL.Opt(IDL.Vec(HazardControl)),
  'location' : IDL.Text,
  'requestedBy' : IDL.Text,
  'toolboxTalk' : IDL.Opt(ToolboxTalk),
  'supervisorOnDuty' : IDL.Opt(IDL.Text),
});
export const RiskStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'draft' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'veryLow' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const RiskRecord = IDL.Record({
  'id' : RecordId,
  'status' : RiskStatus,
  'controls' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'residualLikelihood' : IDL.Nat,
  'residualSeverity' : IDL.Nat,
  'severity' : IDL.Nat,
  'hazard' : IDL.Text,
  'likelihood' : IDL.Nat,
  'riskLevel' : RiskLevel,
  'location' : IDL.Text,
});
export const TrainingStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
});
export const TrainingRecord = IDL.Record({
  'id' : RecordId,
  'status' : TrainingStatus,
  'completionDate' : IDL.Opt(Timestamp),
  'employeeName' : IDL.Text,
  'expiryDate' : IDL.Opt(Timestamp),
  'score' : IDL.Opt(IDL.Nat),
  'employeeId' : IDL.Text,
  'course' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'supervisor' : IDL.Null,
  'systemAdmin' : IDL.Null,
  'ehsManager' : IDL.Null,
  'areaInCharge' : IDL.Null,
  'employee' : IDL.Null,
  'safetyOfficer' : IDL.Null,
  'contractorAdmin' : IDL.Null,
});
export const UserRecord = IDL.Record({
  'id' : UserId,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'role' : UserRole,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'employeeNumber' : IDL.Text,
  'department' : IDL.Text,
});
export const ActivityFeedItem = IDL.Record({
  'id' : RecordId,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'category' : IDL.Text,
});
export const HighRiskAlertDetail = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Text,
  'area' : IDL.Text,
  'dueDate' : IDL.Text,
  'escalationLevel' : IDL.Text,
  'hazard' : IDL.Text,
});
export const IncidentTrendMonth = IDL.Record({
  'low' : IDL.Nat,
  'month' : IDL.Text,
  'high' : IDL.Nat,
  'critical' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const SafetyScoreSplit = IDL.Record({
  'safety' : IDL.Nat,
  'compliance' : IDL.Nat,
  'environment' : IDL.Nat,
  'health' : IDL.Nat,
});
export const ComplianceBreakdown = IDL.Record({
  'legalCompliance' : IDL.Nat,
  'ppeCompliance' : IDL.Nat,
  'iso45001' : IDL.Nat,
  'iso14001' : IDL.Nat,
});
export const ModuleOpenCounts = IDL.Record({
  'incidents' : IDL.Nat,
  'inspections' : IDL.Nat,
  'permits' : IDL.Nat,
  'capaItems' : IDL.Nat,
  'risks' : IDL.Nat,
  'observations' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'auditCompletion' : IDL.Nat,
  'environmentalDeviations' : IDL.Nat,
  'highRiskAlertDetails' : IDL.Vec(HighRiskAlertDetail),
  'openPermits' : IDL.Nat,
  'incidentTrendByMonth' : IDL.Vec(IncidentTrendMonth),
  'safetyScoreSplit' : SafetyScoreSplit,
  'ltifr' : IDL.Float64,
  'highRiskCount' : IDL.Nat,
  'safetyScore' : IDL.Nat,
  'nearMissCount' : IDL.Nat,
  'trainingCompliance' : IDL.Nat,
  'complianceBreakdown' : ComplianceBreakdown,
  'totalIncidents' : IDL.Nat,
  'moduleOpenCounts' : ModuleOpenCounts,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(AttachmentMeta),
  'err' : IDL.Text,
});
export const AuthSession = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : Timestamp,
  'userId' : UserId,
});
export const Result_3 = IDL.Variant({ 'ok' : AuthSession, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : ESGRecord, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'activateUser' : IDL.Func([IDL.Text], [Result], []),
  'addIncidentAttachment' : IDL.Func([IDL.Text, AttachmentMeta], [Result], []),
  'calculateESGScore' : IDL.Func([], [IDL.Float64], ['query']),
  'createCapa' : IDL.Func([CapaRecord], [Result_2], []),
  'createDepartment' : IDL.Func([DepartmentRecord], [Result_2], []),
  'createESGRecord' : IDL.Func([ESGRecord], [Result_2], []),
  'createEnvironmentRecord' : IDL.Func([EnvironmentRecord], [Result_2], []),
  'createIncident' : IDL.Func([IncidentRecord], [Result_2], []),
  'createInspection' : IDL.Func([InspectionRecord], [Result_2], []),
  'createObservation' : IDL.Func([ObservationRecord], [Result_2], []),
  'createPermit' : IDL.Func([PermitRecord], [Result_2], []),
  'createRisk' : IDL.Func([RiskRecord], [Result_2], []),
  'createTrainingRecord' : IDL.Func([TrainingRecord], [Result_2], []),
  'createUser' : IDL.Func([UserRecord], [Result_2], []),
  'deleteCapa' : IDL.Func([IDL.Text], [Result], []),
  'deleteDepartment' : IDL.Func([IDL.Text], [Result], []),
  'deleteESGRecord' : IDL.Func([IDL.Text], [Result], []),
  'deleteEnvironmentRecord' : IDL.Func([IDL.Text], [Result], []),
  'deleteIncident' : IDL.Func([IDL.Text], [Result], []),
  'deleteInspection' : IDL.Func([IDL.Text], [Result], []),
  'deleteObservation' : IDL.Func([IDL.Text], [Result], []),
  'deletePermit' : IDL.Func([IDL.Text], [Result], []),
  'deleteRisk' : IDL.Func([IDL.Text], [Result], []),
  'deleteTrainingRecord' : IDL.Func([IDL.Text], [Result], []),
  'deleteUser' : IDL.Func([IDL.Text], [Result], []),
  'getActivityFeed' : IDL.Func([], [IDL.Vec(ActivityFeedItem)], ['query']),
  'getCapas' : IDL.Func([], [IDL.Vec(CapaRecord)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(DepartmentRecord)], ['query']),
  'getESGRecords' : IDL.Func([], [IDL.Vec(ESGRecord)], ['query']),
  'getESGRecordsByPeriod' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ESGRecord)],
      ['query'],
    ),
  'getEnvironmentRecords' : IDL.Func(
      [],
      [IDL.Vec(EnvironmentRecord)],
      ['query'],
    ),
  'getIncident' : IDL.Func([IDL.Text], [IDL.Opt(IncidentRecord)], ['query']),
  'getIncidentAttachments' : IDL.Func([IDL.Text], [Result_4], ['query']),
  'getIncidents' : IDL.Func([], [IDL.Vec(IncidentRecord)], ['query']),
  'getInspections' : IDL.Func([], [IDL.Vec(InspectionRecord)], ['query']),
  'getNotifLastRead' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getObservations' : IDL.Func([], [IDL.Vec(ObservationRecord)], ['query']),
  'getPermit' : IDL.Func([IDL.Text], [IDL.Opt(PermitRecord)], ['query']),
  'getPermits' : IDL.Func([], [IDL.Vec(PermitRecord)], ['query']),
  'getRisks' : IDL.Func([], [IDL.Vec(RiskRecord)], ['query']),
  'getTrainingRecords' : IDL.Func([], [IDL.Vec(TrainingRecord)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'removeIncidentAttachment' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'runDeadlineChecks' : IDL.Func([], [], []),
  'seedMockData' : IDL.Func([], [IDL.Text], []),
  'sendTestNotification' : IDL.Func([], [IDL.Text], []),
  'updateCapa' : IDL.Func([IDL.Text, CapaRecord], [Result], []),
  'updateCapaStatus' : IDL.Func([IDL.Text, CapaStatus], [Result], []),
  'updateESGRecord' : IDL.Func([ESGRecord], [Result_2], []),
  'updateESGStatus' : IDL.Func(
      [IDL.Text, ESGStatus, IDL.Text, Timestamp],
      [Result_1],
      [],
    ),
  'updateIncident' : IDL.Func([IDL.Text, IncidentRecord], [Result], []),
  'updateIncidentStatus' : IDL.Func([IDL.Text, IncidentStatus], [Result], []),
  'updateInspectionStatus' : IDL.Func(
      [IDL.Text, InspectionStatus],
      [Result],
      [],
    ),
  'updateObservation' : IDL.Func([IDL.Text, ObservationRecord], [Result], []),
  'updateObservationStatus' : IDL.Func(
      [IDL.Text, ObservationStatus],
      [Result],
      [],
    ),
  'updatePermitStatus' : IDL.Func(
      [IDL.Text, PermitStatus, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'updateRiskStatus' : IDL.Func([IDL.Text, RiskStatus], [Result], []),
  'updateTrainingStatus' : IDL.Func([IDL.Text, TrainingStatus], [Result], []),
  'updateUser' : IDL.Func([IDL.Text, UserRecord], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AttachmentMeta = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Text,
    'storageHash' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'uploadedAt' : IDL.Int,
  });
  const RecordId = IDL.Text;
  const CapaStatus = IDL.Variant({
    'closed' : IDL.Null,
    'verified' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CapaRecord = IDL.Record({
    'id' : RecordId,
    'status' : CapaStatus,
    'title' : IDL.Text,
    'owner' : IDL.Text,
    'createdAt' : Timestamp,
    'actionPlan' : IDL.Text,
    'verificationDetails' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'targetDate' : Timestamp,
    'department' : IDL.Text,
    'rootCause' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const DepartmentRecord = IDL.Record({
    'id' : RecordId,
    'head' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  const ESGStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ESGSocial = IDL.Record({
    'womenInWorkforce' : IDL.Float64,
    'occupationalHealthCases' : IDL.Float64,
    'fatalities' : IDL.Float64,
    'genderDiversityRatio' : IDL.Float64,
    'trir' : IDL.Float64,
    'employeeSatisfactionIndex' : IDL.Float64,
    'ltifr' : IDL.Float64,
    'contractorSafetyPerformance' : IDL.Float64,
    'absenteeismRate' : IDL.Float64,
    'grievanceCases' : IDL.Float64,
    'trainingHoursPerEmployee' : IDL.Float64,
    'communityEngagementPrograms' : IDL.Float64,
    'employeeTurnoverRate' : IDL.Float64,
  });
  const UserId = IDL.Text;
  const ESGEnvironmental = IDL.Record({
    'wasteRecyclingRate' : IDL.Float64,
    'envComplianceViolations' : IDL.Float64,
    'renewableEnergyUsage' : IDL.Float64,
    'waterReuseRate' : IDL.Float64,
    'energyConsumption' : IDL.Float64,
    'waterIntensity' : IDL.Float64,
    'waterConsumption' : IDL.Float64,
    'carbonEmissionIntensity' : IDL.Float64,
    'wasteGenerated' : IDL.Float64,
  });
  const ESGGovernance = IDL.Record({
    'antiCorruptionTrainingCoverage' : IDL.Float64,
    'complianceBreaches' : IDL.Float64,
    'regulatoryViolations' : IDL.Float64,
    'whistleblowerComplaints' : IDL.Float64,
    'codeOfConductViolations' : IDL.Float64,
    'policyComplianceScore' : IDL.Float64,
    'dataPrivacyIncidents' : IDL.Float64,
    'regulatoryPenalties' : IDL.Float64,
  });
  const ESGRecord = IDL.Record({
    'id' : RecordId,
    'status' : ESGStatus,
    'periodType' : IDL.Text,
    'dataSource' : IDL.Text,
    'social' : ESGSocial,
    'period' : IDL.Text,
    'approvedAt' : Timestamp,
    'approvedBy' : IDL.Text,
    'recordedAt' : Timestamp,
    'recordedBy' : UserId,
    'recordedByName' : IDL.Text,
    'notes' : IDL.Text,
    'environmental' : ESGEnvironmental,
    'governance' : ESGGovernance,
    'department' : IDL.Text,
  });
  const EnvironmentRecord = IDL.Record({
    'id' : RecordId,
    'value' : IDL.Float64,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'recordType' : IDL.Text,
    'recordedBy' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const IncidentStatus = IDL.Variant({
    'closed' : IDL.Null,
    'submitted' : IDL.Null,
    'escalated' : IDL.Null,
    'underReview' : IDL.Null,
    'approved' : IDL.Null,
    'overdue' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const PersonInvolved = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'employeeId' : IDL.Text,
    'injuryType' : IDL.Text,
    'department' : IDL.Text,
  });
  const IncidentRecord = IDL.Record({
    'id' : RecordId,
    'status' : IncidentStatus,
    'title' : IDL.Text,
    'teamLead' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'areaBarricaded' : IDL.Opt(IDL.Bool),
    'description' : IDL.Text,
    'personsInvolved' : IDL.Opt(IDL.Vec(PersonInvolved)),
    'ticketNumber' : IDL.Text,
    'teamMembers' : IDL.Opt(IDL.Vec(IDL.Text)),
    'updatedAt' : Timestamp,
    'reportedBy' : IDL.Text,
    'medicalTreatment' : IDL.Opt(IDL.Bool),
    'investigationDueDate' : IDL.Opt(IDL.Text),
    'targetDate' : IDL.Opt(IDL.Text),
    'natureOfInjury' : IDL.Opt(IDL.Text),
    'actionsTaken' : IDL.Opt(IDL.Text),
    'rootCauseCategory' : IDL.Opt(IDL.Text),
    'severity' : IDL.Text,
    'bodyPartAffected' : IDL.Opt(IDL.Text),
    'contributingFactors' : IDL.Opt(IDL.Vec(IDL.Text)),
    'department' : IDL.Text,
    'firstAidGiven' : IDL.Opt(IDL.Bool),
    'correctiveAction' : IDL.Opt(IDL.Text),
    'daysLost' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
    'attachments' : IDL.Opt(IDL.Vec(AttachmentMeta)),
    'rootCause' : IDL.Opt(IDL.Text),
    'responsiblePerson' : IDL.Opt(IDL.Text),
  });
  const InspectionStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const InspectionRecord = IDL.Record({
    'id' : RecordId,
    'status' : InspectionStatus,
    'inspectionDate' : Timestamp,
    'title' : IDL.Text,
    'area' : IDL.Text,
    'createdAt' : Timestamp,
    'score' : IDL.Nat,
    'findings' : IDL.Vec(IDL.Text),
    'inspector' : IDL.Text,
  });
  const ObservationStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ObservationType = IDL.Variant({
    'unsafeAct' : IDL.Null,
    'nearMiss' : IDL.Null,
    'unsafeCondition' : IDL.Null,
  });
  const ObservationRecord = IDL.Record({
    'id' : RecordId,
    'status' : ObservationStatus,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'actions' : IDL.Vec(IDL.Text),
    'reportedBy' : IDL.Text,
    'obsType' : ObservationType,
    'location' : IDL.Text,
    'attachments' : IDL.Opt(IDL.Vec(AttachmentMeta)),
  });
  const PermitStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'submitted' : IDL.Null,
    'underReview' : IDL.Null,
    'validated' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const GasTestResults = IDL.Record({
    'oxygenLevel' : IDL.Text,
    'testTime' : IDL.Text,
    'testedBy' : IDL.Text,
    'toxicGas' : IDL.Text,
    'flammableGas' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PermitType = IDL.Variant({
    'confinedSpace' : IDL.Null,
    'heightWork' : IDL.Null,
    'lineBreaking' : IDL.Null,
    'hotWork' : IDL.Null,
    'electrical' : IDL.Null,
    'excavation' : IDL.Null,
  });
  const PermitSignatures = IDL.Record({
    'safetyOfficerSignature' : IDL.Text,
    'requestedBySignature' : IDL.Text,
    'supervisorSignature' : IDL.Text,
  });
  const HazardControl = IDL.Record({
    'control' : IDL.Text,
    'residualRisk' : IDL.Text,
    'hazard' : IDL.Text,
  });
  const ToolboxTalk = IDL.Record({
    'keyPoints' : IDL.Text,
    'conductedAt' : IDL.Text,
    'conductedBy' : IDL.Text,
    'attendeesCount' : IDL.Nat,
  });
  const PermitRecord = IDL.Record({
    'id' : RecordId,
    'startTime' : Timestamp,
    'status' : PermitStatus,
    'isolationVerifiedBy' : IDL.Opt(IDL.Text),
    'hazards' : IDL.Vec(IDL.Text),
    'endTime' : Timestamp,
    'permitNumber' : IDL.Text,
    'lotoApplied' : IDL.Opt(IDL.Bool),
    'approvedBy' : IDL.Opt(IDL.Text),
    'ppeRequired' : IDL.Vec(IDL.Text),
    'jobDescription' : IDL.Text,
    'createdAt' : Timestamp,
    'gasTestResults' : IDL.Opt(GasTestResults),
    'emergencyContacts' : IDL.Opt(IDL.Vec(EmergencyContact)),
    'reviewedBy' : IDL.Opt(IDL.Text),
    'permitType' : PermitType,
    'isolationTypes' : IDL.Opt(IDL.Vec(IDL.Text)),
    'signatures' : IDL.Opt(PermitSignatures),
    'hazardControls' : IDL.Opt(IDL.Vec(HazardControl)),
    'location' : IDL.Text,
    'requestedBy' : IDL.Text,
    'toolboxTalk' : IDL.Opt(ToolboxTalk),
    'supervisorOnDuty' : IDL.Opt(IDL.Text),
  });
  const RiskStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'draft' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'veryLow' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RiskRecord = IDL.Record({
    'id' : RecordId,
    'status' : RiskStatus,
    'controls' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'residualLikelihood' : IDL.Nat,
    'residualSeverity' : IDL.Nat,
    'severity' : IDL.Nat,
    'hazard' : IDL.Text,
    'likelihood' : IDL.Nat,
    'riskLevel' : RiskLevel,
    'location' : IDL.Text,
  });
  const TrainingStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const TrainingRecord = IDL.Record({
    'id' : RecordId,
    'status' : TrainingStatus,
    'completionDate' : IDL.Opt(Timestamp),
    'employeeName' : IDL.Text,
    'expiryDate' : IDL.Opt(Timestamp),
    'score' : IDL.Opt(IDL.Nat),
    'employeeId' : IDL.Text,
    'course' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'supervisor' : IDL.Null,
    'systemAdmin' : IDL.Null,
    'ehsManager' : IDL.Null,
    'areaInCharge' : IDL.Null,
    'employee' : IDL.Null,
    'safetyOfficer' : IDL.Null,
    'contractorAdmin' : IDL.Null,
  });
  const UserRecord = IDL.Record({
    'id' : UserId,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'role' : UserRole,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'employeeNumber' : IDL.Text,
    'department' : IDL.Text,
  });
  const ActivityFeedItem = IDL.Record({
    'id' : RecordId,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'category' : IDL.Text,
  });
  const HighRiskAlertDetail = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Text,
    'area' : IDL.Text,
    'dueDate' : IDL.Text,
    'escalationLevel' : IDL.Text,
    'hazard' : IDL.Text,
  });
  const IncidentTrendMonth = IDL.Record({
    'low' : IDL.Nat,
    'month' : IDL.Text,
    'high' : IDL.Nat,
    'critical' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const SafetyScoreSplit = IDL.Record({
    'safety' : IDL.Nat,
    'compliance' : IDL.Nat,
    'environment' : IDL.Nat,
    'health' : IDL.Nat,
  });
  const ComplianceBreakdown = IDL.Record({
    'legalCompliance' : IDL.Nat,
    'ppeCompliance' : IDL.Nat,
    'iso45001' : IDL.Nat,
    'iso14001' : IDL.Nat,
  });
  const ModuleOpenCounts = IDL.Record({
    'incidents' : IDL.Nat,
    'inspections' : IDL.Nat,
    'permits' : IDL.Nat,
    'capaItems' : IDL.Nat,
    'risks' : IDL.Nat,
    'observations' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'auditCompletion' : IDL.Nat,
    'environmentalDeviations' : IDL.Nat,
    'highRiskAlertDetails' : IDL.Vec(HighRiskAlertDetail),
    'openPermits' : IDL.Nat,
    'incidentTrendByMonth' : IDL.Vec(IncidentTrendMonth),
    'safetyScoreSplit' : SafetyScoreSplit,
    'ltifr' : IDL.Float64,
    'highRiskCount' : IDL.Nat,
    'safetyScore' : IDL.Nat,
    'nearMissCount' : IDL.Nat,
    'trainingCompliance' : IDL.Nat,
    'complianceBreakdown' : ComplianceBreakdown,
    'totalIncidents' : IDL.Nat,
    'moduleOpenCounts' : ModuleOpenCounts,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Vec(AttachmentMeta),
    'err' : IDL.Text,
  });
  const AuthSession = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : Timestamp,
    'userId' : UserId,
  });
  const Result_3 = IDL.Variant({ 'ok' : AuthSession, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : ESGRecord, 'err' : IDL.Text });
  
  return IDL.Service({
    'activateUser' : IDL.Func([IDL.Text], [Result], []),
    'addIncidentAttachment' : IDL.Func(
        [IDL.Text, AttachmentMeta],
        [Result],
        [],
      ),
    'calculateESGScore' : IDL.Func([], [IDL.Float64], ['query']),
    'createCapa' : IDL.Func([CapaRecord], [Result_2], []),
    'createDepartment' : IDL.Func([DepartmentRecord], [Result_2], []),
    'createESGRecord' : IDL.Func([ESGRecord], [Result_2], []),
    'createEnvironmentRecord' : IDL.Func([EnvironmentRecord], [Result_2], []),
    'createIncident' : IDL.Func([IncidentRecord], [Result_2], []),
    'createInspection' : IDL.Func([InspectionRecord], [Result_2], []),
    'createObservation' : IDL.Func([ObservationRecord], [Result_2], []),
    'createPermit' : IDL.Func([PermitRecord], [Result_2], []),
    'createRisk' : IDL.Func([RiskRecord], [Result_2], []),
    'createTrainingRecord' : IDL.Func([TrainingRecord], [Result_2], []),
    'createUser' : IDL.Func([UserRecord], [Result_2], []),
    'deleteCapa' : IDL.Func([IDL.Text], [Result], []),
    'deleteDepartment' : IDL.Func([IDL.Text], [Result], []),
    'deleteESGRecord' : IDL.Func([IDL.Text], [Result], []),
    'deleteEnvironmentRecord' : IDL.Func([IDL.Text], [Result], []),
    'deleteIncident' : IDL.Func([IDL.Text], [Result], []),
    'deleteInspection' : IDL.Func([IDL.Text], [Result], []),
    'deleteObservation' : IDL.Func([IDL.Text], [Result], []),
    'deletePermit' : IDL.Func([IDL.Text], [Result], []),
    'deleteRisk' : IDL.Func([IDL.Text], [Result], []),
    'deleteTrainingRecord' : IDL.Func([IDL.Text], [Result], []),
    'deleteUser' : IDL.Func([IDL.Text], [Result], []),
    'getActivityFeed' : IDL.Func([], [IDL.Vec(ActivityFeedItem)], ['query']),
    'getCapas' : IDL.Func([], [IDL.Vec(CapaRecord)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(DepartmentRecord)], ['query']),
    'getESGRecords' : IDL.Func([], [IDL.Vec(ESGRecord)], ['query']),
    'getESGRecordsByPeriod' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ESGRecord)],
        ['query'],
      ),
    'getEnvironmentRecords' : IDL.Func(
        [],
        [IDL.Vec(EnvironmentRecord)],
        ['query'],
      ),
    'getIncident' : IDL.Func([IDL.Text], [IDL.Opt(IncidentRecord)], ['query']),
    'getIncidentAttachments' : IDL.Func([IDL.Text], [Result_4], ['query']),
    'getIncidents' : IDL.Func([], [IDL.Vec(IncidentRecord)], ['query']),
    'getInspections' : IDL.Func([], [IDL.Vec(InspectionRecord)], ['query']),
    'getNotifLastRead' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getObservations' : IDL.Func([], [IDL.Vec(ObservationRecord)], ['query']),
    'getPermit' : IDL.Func([IDL.Text], [IDL.Opt(PermitRecord)], ['query']),
    'getPermits' : IDL.Func([], [IDL.Vec(PermitRecord)], ['query']),
    'getRisks' : IDL.Func([], [IDL.Vec(RiskRecord)], ['query']),
    'getTrainingRecords' : IDL.Func([], [IDL.Vec(TrainingRecord)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'removeIncidentAttachment' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'runDeadlineChecks' : IDL.Func([], [], []),
    'seedMockData' : IDL.Func([], [IDL.Text], []),
    'sendTestNotification' : IDL.Func([], [IDL.Text], []),
    'updateCapa' : IDL.Func([IDL.Text, CapaRecord], [Result], []),
    'updateCapaStatus' : IDL.Func([IDL.Text, CapaStatus], [Result], []),
    'updateESGRecord' : IDL.Func([ESGRecord], [Result_2], []),
    'updateESGStatus' : IDL.Func(
        [IDL.Text, ESGStatus, IDL.Text, Timestamp],
        [Result_1],
        [],
      ),
    'updateIncident' : IDL.Func([IDL.Text, IncidentRecord], [Result], []),
    'updateIncidentStatus' : IDL.Func([IDL.Text, IncidentStatus], [Result], []),
    'updateInspectionStatus' : IDL.Func(
        [IDL.Text, InspectionStatus],
        [Result],
        [],
      ),
    'updateObservation' : IDL.Func([IDL.Text, ObservationRecord], [Result], []),
    'updateObservationStatus' : IDL.Func(
        [IDL.Text, ObservationStatus],
        [Result],
        [],
      ),
    'updatePermitStatus' : IDL.Func(
        [IDL.Text, PermitStatus, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'updateRiskStatus' : IDL.Func([IDL.Text, RiskStatus], [Result], []),
    'updateTrainingStatus' : IDL.Func([IDL.Text, TrainingStatus], [Result], []),
    'updateUser' : IDL.Func([IDL.Text, UserRecord], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };