/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityFeedItem {
  'id' : RecordId,
  'message' : string,
  'timestamp' : Timestamp,
  'category' : string,
}
export interface AttachmentMeta {
  'id' : string,
  'contentType' : string,
  'storageHash' : string,
  'name' : string,
  'size' : bigint,
  'uploadedAt' : bigint,
}
export interface AuthSession {
  'token' : string,
  'expiresAt' : Timestamp,
  'userId' : UserId,
}
export interface CapaRecord {
  'id' : RecordId,
  'status' : CapaStatus,
  'title' : string,
  'owner' : string,
  'createdAt' : Timestamp,
  'actionPlan' : string,
  'verificationDetails' : [] | [string],
  'updatedAt' : Timestamp,
  'targetDate' : Timestamp,
  'department' : string,
  'rootCause' : string,
}
export type CapaStatus = { 'closed' : null } |
  { 'verified' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface ComplianceBreakdown {
  'legalCompliance' : bigint,
  'ppeCompliance' : bigint,
  'iso45001' : bigint,
  'iso14001' : bigint,
}
export interface DashboardStats {
  'auditCompletion' : bigint,
  'environmentalDeviations' : bigint,
  'highRiskAlertDetails' : Array<HighRiskAlertDetail>,
  'openPermits' : bigint,
  'incidentTrendByMonth' : Array<IncidentTrendMonth>,
  'safetyScoreSplit' : SafetyScoreSplit,
  'ltifr' : number,
  'highRiskCount' : bigint,
  'safetyScore' : bigint,
  'nearMissCount' : bigint,
  'trainingCompliance' : bigint,
  'complianceBreakdown' : ComplianceBreakdown,
  'totalIncidents' : bigint,
  'moduleOpenCounts' : ModuleOpenCounts,
}
export interface DepartmentRecord {
  'id' : RecordId,
  'head' : string,
  'name' : string,
  'location' : string,
}
export interface ESGEnvironmental {
  'wasteRecyclingRate' : number,
  'envComplianceViolations' : number,
  'renewableEnergyUsage' : number,
  'waterReuseRate' : number,
  'energyConsumption' : number,
  'waterIntensity' : number,
  'waterConsumption' : number,
  'carbonEmissionIntensity' : number,
  'wasteGenerated' : number,
}
export interface ESGGovernance {
  'antiCorruptionTrainingCoverage' : number,
  'complianceBreaches' : number,
  'regulatoryViolations' : number,
  'whistleblowerComplaints' : number,
  'codeOfConductViolations' : number,
  'policyComplianceScore' : number,
  'dataPrivacyIncidents' : number,
  'regulatoryPenalties' : number,
}
export interface ESGRecord {
  'id' : RecordId,
  'status' : ESGStatus,
  'periodType' : string,
  'dataSource' : string,
  'social' : ESGSocial,
  'period' : string,
  'approvedAt' : Timestamp,
  'approvedBy' : string,
  'recordedAt' : Timestamp,
  'recordedBy' : UserId,
  'recordedByName' : string,
  'notes' : string,
  'environmental' : ESGEnvironmental,
  'governance' : ESGGovernance,
  'department' : string,
}
export interface ESGSocial {
  'womenInWorkforce' : number,
  'occupationalHealthCases' : number,
  'fatalities' : number,
  'genderDiversityRatio' : number,
  'trir' : number,
  'employeeSatisfactionIndex' : number,
  'ltifr' : number,
  'contractorSafetyPerformance' : number,
  'absenteeismRate' : number,
  'grievanceCases' : number,
  'trainingHoursPerEmployee' : number,
  'communityEngagementPrograms' : number,
  'employeeTurnoverRate' : number,
}
export type ESGStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface EmergencyContact {
  'name' : string,
  'role' : string,
  'phone' : string,
}
export interface EnvironmentRecord {
  'id' : RecordId,
  'value' : number,
  'createdAt' : Timestamp,
  'unit' : string,
  'recordType' : string,
  'recordedBy' : string,
  'notes' : [] | [string],
  'location' : string,
}
export interface GasTestResults {
  'oxygenLevel' : string,
  'testTime' : string,
  'testedBy' : string,
  'toxicGas' : string,
  'flammableGas' : string,
}
export interface HazardControl {
  'control' : string,
  'residualRisk' : string,
  'hazard' : string,
}
export interface HighRiskAlertDetail {
  'id' : string,
  'owner' : string,
  'area' : string,
  'dueDate' : string,
  'escalationLevel' : string,
  'hazard' : string,
}
export interface IncidentRecord {
  'id' : RecordId,
  'status' : IncidentStatus,
  'title' : string,
  'teamLead' : [] | [string],
  'createdAt' : Timestamp,
  'areaBarricaded' : [] | [boolean],
  'description' : string,
  'personsInvolved' : [] | [Array<PersonInvolved>],
  'ticketNumber' : string,
  'teamMembers' : [] | [Array<string>],
  'updatedAt' : Timestamp,
  'reportedBy' : string,
  'medicalTreatment' : [] | [boolean],
  'investigationDueDate' : [] | [string],
  'targetDate' : [] | [string],
  'natureOfInjury' : [] | [string],
  'actionsTaken' : [] | [string],
  'rootCauseCategory' : [] | [string],
  'severity' : string,
  'bodyPartAffected' : [] | [string],
  'contributingFactors' : [] | [Array<string>],
  'department' : string,
  'firstAidGiven' : [] | [boolean],
  'correctiveAction' : [] | [string],
  'daysLost' : [] | [bigint],
  'location' : string,
  'attachments' : [] | [Array<AttachmentMeta>],
  'rootCause' : [] | [string],
  'responsiblePerson' : [] | [string],
}
export type IncidentStatus = { 'closed' : null } |
  { 'submitted' : null } |
  { 'escalated' : null } |
  { 'underReview' : null } |
  { 'approved' : null } |
  { 'overdue' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface IncidentTrendMonth {
  'low' : bigint,
  'month' : string,
  'high' : bigint,
  'critical' : bigint,
  'medium' : bigint,
}
export interface InspectionRecord {
  'id' : RecordId,
  'status' : InspectionStatus,
  'inspectionDate' : Timestamp,
  'title' : string,
  'area' : string,
  'createdAt' : Timestamp,
  'score' : bigint,
  'findings' : Array<string>,
  'inspector' : string,
}
export type InspectionStatus = { 'scheduled' : null } |
  { 'completed' : null } |
  { 'overdue' : null } |
  { 'inProgress' : null };
export interface ModuleOpenCounts {
  'incidents' : bigint,
  'inspections' : bigint,
  'permits' : bigint,
  'capaItems' : bigint,
  'risks' : bigint,
  'observations' : bigint,
}
export interface ObservationRecord {
  'id' : RecordId,
  'status' : ObservationStatus,
  'createdAt' : Timestamp,
  'description' : string,
  'actions' : Array<string>,
  'reportedBy' : string,
  'obsType' : ObservationType,
  'location' : string,
  'attachments' : [] | [Array<AttachmentMeta>],
}
export type ObservationStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type ObservationType = { 'unsafeAct' : null } |
  { 'nearMiss' : null } |
  { 'unsafeCondition' : null };
export interface PermitRecord {
  'id' : RecordId,
  'startTime' : Timestamp,
  'status' : PermitStatus,
  'isolationVerifiedBy' : [] | [string],
  'hazards' : Array<string>,
  'endTime' : Timestamp,
  'permitNumber' : string,
  'lotoApplied' : [] | [boolean],
  'approvedBy' : [] | [string],
  'ppeRequired' : Array<string>,
  'jobDescription' : string,
  'createdAt' : Timestamp,
  'gasTestResults' : [] | [GasTestResults],
  'emergencyContacts' : [] | [Array<EmergencyContact>],
  'reviewedBy' : [] | [string],
  'permitType' : PermitType,
  'isolationTypes' : [] | [Array<string>],
  'signatures' : [] | [PermitSignatures],
  'hazardControls' : [] | [Array<HazardControl>],
  'location' : string,
  'requestedBy' : string,
  'toolboxTalk' : [] | [ToolboxTalk],
  'supervisorOnDuty' : [] | [string],
}
export interface PermitSignatures {
  'safetyOfficerSignature' : string,
  'requestedBySignature' : string,
  'supervisorSignature' : string,
}
export type PermitStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'expired' : null } |
  { 'submitted' : null } |
  { 'underReview' : null } |
  { 'validated' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export type PermitType = { 'confinedSpace' : null } |
  { 'heightWork' : null } |
  { 'liftingPermit' : null } |
  { 'lineBreaking' : null } |
  { 'hotWork' : null } |
  { 'generalWorkPermit' : null } |
  { 'electrical' : null } |
  { 'excavation' : null };
export interface PersonInvolved {
  'name' : string,
  'role' : string,
  'employeeId' : string,
  'injuryType' : string,
  'department' : string,
}
export type RecordId = string;
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_2 = { 'ok' : ESGRecord } |
  { 'err' : string };
export type Result_3 = { 'ok' : string } |
  { 'err' : string };
export type Result_4 = { 'ok' : AuthSession } |
  { 'err' : string };
export type Result_5 = { 'ok' : Array<AttachmentMeta> } |
  { 'err' : string };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'veryLow' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface RiskRecord {
  'id' : RecordId,
  'status' : RiskStatus,
  'controls' : Array<string>,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'residualLikelihood' : bigint,
  'residualSeverity' : bigint,
  'severity' : bigint,
  'hazard' : string,
  'likelihood' : bigint,
  'riskLevel' : RiskLevel,
  'location' : string,
}
export type RiskStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'draft' : null };
export interface SafetyScoreSplit {
  'safety' : bigint,
  'compliance' : bigint,
  'environment' : bigint,
  'health' : bigint,
}
export type Timestamp = bigint;
export interface ToolboxTalk {
  'keyPoints' : string,
  'conductedAt' : string,
  'conductedBy' : string,
  'attendeesCount' : bigint,
}
export interface TrainingRecord {
  'id' : RecordId,
  'status' : TrainingStatus,
  'completionDate' : [] | [Timestamp],
  'employeeName' : string,
  'expiryDate' : [] | [Timestamp],
  'score' : [] | [bigint],
  'employeeId' : string,
  'course' : string,
}
export type TrainingStatus = { 'notStarted' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'overdue' : null };
export type UserId = string;
export interface UserRecord {
  'id' : UserId,
  'active' : boolean,
  'name' : string,
  'role' : UserRole,
  'mobileNumber' : string,
  'email' : string,
  'employeeNumber' : string,
  'department' : string,
}
export type UserRole = { 'departmentHOD' : null } |
  { 'supervisor' : null } |
  { 'systemAdmin' : null } |
  { 'ehsManager' : null } |
  { 'areaInCharge' : null } |
  { 'employee' : null } |
  { 'safetyOfficer' : null } |
  { 'contractorAdmin' : null };
export interface _SERVICE {
  'activateUser' : ActorMethod<[string], Result_1>,
  'addIncidentAttachment' : ActorMethod<[string, AttachmentMeta], Result_1>,
  'calculateESGScore' : ActorMethod<[], number>,
  'createCapa' : ActorMethod<[CapaRecord], Result_3>,
  'createDepartment' : ActorMethod<[DepartmentRecord], Result_3>,
  'createESGRecord' : ActorMethod<[ESGRecord], Result_3>,
  'createEnvironmentRecord' : ActorMethod<[EnvironmentRecord], Result_3>,
  'createIncident' : ActorMethod<[IncidentRecord], Result_3>,
  'createInspection' : ActorMethod<[InspectionRecord], Result_3>,
  'createObservation' : ActorMethod<[ObservationRecord], Result_3>,
  'createPermit' : ActorMethod<[PermitRecord], Result_3>,
  'createRisk' : ActorMethod<[RiskRecord], Result_3>,
  'createTrainingRecord' : ActorMethod<[TrainingRecord], Result_3>,
  'createUser' : ActorMethod<[UserRecord], Result_3>,
  'deleteCapa' : ActorMethod<[string], Result_1>,
  'deleteDepartment' : ActorMethod<[string], Result_1>,
  'deleteESGRecord' : ActorMethod<[string], Result_1>,
  'deleteEnvironmentRecord' : ActorMethod<[string], Result_1>,
  'deleteIncident' : ActorMethod<[string], Result_1>,
  'deleteInspection' : ActorMethod<[string], Result_1>,
  'deleteObservation' : ActorMethod<[string], Result_1>,
  'deletePermit' : ActorMethod<[string], Result_1>,
  'deleteRisk' : ActorMethod<[string], Result_1>,
  'deleteTrainingRecord' : ActorMethod<[string], Result_1>,
  'deleteUser' : ActorMethod<[string], Result_1>,
  'getActivityFeed' : ActorMethod<[], Array<ActivityFeedItem>>,
  'getCapas' : ActorMethod<[], Array<CapaRecord>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDepartments' : ActorMethod<[], Array<DepartmentRecord>>,
  'getESGRecords' : ActorMethod<[], Array<ESGRecord>>,
  'getESGRecordsByPeriod' : ActorMethod<[string], Array<ESGRecord>>,
  'getEnvironmentRecords' : ActorMethod<[], Array<EnvironmentRecord>>,
  'getIncident' : ActorMethod<[string], [] | [IncidentRecord]>,
  'getIncidentAttachments' : ActorMethod<[string], Result_5>,
  'getIncidents' : ActorMethod<[], Array<IncidentRecord>>,
  'getInspections' : ActorMethod<[], Array<InspectionRecord>>,
  'getNotifLastRead' : ActorMethod<[], [] | [bigint]>,
  'getObservations' : ActorMethod<[], Array<ObservationRecord>>,
  'getPermit' : ActorMethod<[string], [] | [PermitRecord]>,
  'getPermits' : ActorMethod<[], Array<PermitRecord>>,
  'getRisks' : ActorMethod<[], Array<RiskRecord>>,
  'getTrainingRecords' : ActorMethod<[], Array<TrainingRecord>>,
  'getUsers' : ActorMethod<[], Array<UserRecord>>,
  'login' : ActorMethod<[string, string], Result_4>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'removeIncidentAttachment' : ActorMethod<[string, string], Result_1>,
  'runDeadlineChecks' : ActorMethod<[], undefined>,
  'seedMockData' : ActorMethod<[], string>,
  'sendMobileOtp' : ActorMethod<[string, string], Result_3>,
  'sendTestNotification' : ActorMethod<[], string>,
  'updateCapa' : ActorMethod<[string, CapaRecord], Result_1>,
  'updateCapaStatus' : ActorMethod<[string, CapaStatus], Result_1>,
  'updateESGRecord' : ActorMethod<[ESGRecord], Result_3>,
  'updateESGStatus' : ActorMethod<
    [string, ESGStatus, string, Timestamp],
    Result_2
  >,
  'updateIncident' : ActorMethod<[string, IncidentRecord], Result_1>,
  'updateIncidentStatus' : ActorMethod<[string, IncidentStatus], Result_1>,
  'updateInspectionStatus' : ActorMethod<[string, InspectionStatus], Result_1>,
  'updateObservation' : ActorMethod<[string, ObservationRecord], Result_1>,
  'updateObservationStatus' : ActorMethod<
    [string, ObservationStatus],
    Result_1
  >,
  'updatePermitStatus' : ActorMethod<
    [string, PermitStatus, string, string],
    Result_1
  >,
  'updateRiskStatus' : ActorMethod<[string, RiskStatus], Result_1>,
  'updateTrainingStatus' : ActorMethod<[string, TrainingStatus], Result_1>,
  'updateUser' : ActorMethod<[string, UserRecord], Result_1>,
  'verifyMobileOtp' : ActorMethod<[string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];